export const YEARS: number[] = [
  2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016,
];

export const FIRST_TIME_ORGANOZATIONS: number = 14;

export const CATEGORIES: Record<string, number> = {
  "Science and medicine": 116,
  Data: 73,
  Security: 30,
  "Development tools": 42,
  Media: 51,
  "Programming languages": 108,
  "Artificial Intelligence": 47,
  "Operating systems": 36,
  Other: 48,
  "End user applications": 87,
  "Social and communication": 19,
  "Infrastructure and cloud": 49,
  Web: 45,
};

export const TOPICS: Record<string, number> = {
  robotics: 21,
  "3d": 4,
  slam: 2,
  mapping: 3,
  "point clouds": 2,
  "citizen science": 2,
  "spatial information infrastructures": 1,
  "open standards": 1,
  "data analytics": 5,
  Geoinformation: 1,
  dependencies: 1,
  vulnerabilities: 2,
  SoftwareCompositionAnalysis: 1,
  License: 1,
  SBOM: 2,
  graphics: 29,
  media: 6,
  animation: 4,
  "Visual Effects": 1,
  Film: 1,
  "natural language processing": 9,
  "data modeling": 1,
  "legal technology": 1,
  "contract management": 1,
  "document assembly": 1,
  "space applications": 2,
  "signal processing": 2,
  "software defined radio": 3,
  cubesats: 1,
  simulations: 1,
  fuzzing: 3,
  ci: 1,
  education: 28,
  "machine learning": 45,
  "artificial intelligence": 15,
  "open education": 1,
  "deep learning": 12,
  neuroscience: 6,
  radiology: 2,
  heathcare: 1,
  "Polar Science": 1,
  "operating systems": 8,
  networking: 16,
  streaming: 6,
  "web servers": 1,
  "mobile-apps": 1,
  "bug finding": 2,
  "developer tools": 8,
  web: 65,
  "mobile programming": 2,
  mobile: 14,
  "web programming": 2,
  android: 3,
  "user generated content": 1,
  Flashcards: 1,
  backend: 1,
  databases: 9,
  "big data": 10,
  OLAP: 1,
  "machine translation": 1,
  "language technology": 1,
  "less-resources languages": 1,
  "computer vision": 16,
  linux: 7,
  camera: 2,
  "image processing": 5,
  "digital hardware design": 1,
  automation: 13,
  apis: 2,
  "code generation": 1,
  "api description": 1,
  testing: 6,
  api: 6,
  GenAI: 1,
  simulation: 11,
  rendering: 4,
  "computer graphics": 1,
  "image synthesis": 1,
  "computer architecture": 1,
  "processor design": 1,
  simulators: 1,
  interactivity: 2,
  electronics: 1,
  ai: 26,
  Drone: 1,
  "autonomous vehicle": 1,
  "unmanned vehicle": 1,
  engineering: 3,
  "system modelling": 1,
  "mathematical software": 2,
  solver: 1,
  cloud: 38,
  Architectures: 1,
  audio: 9,
  editing: 2,
  compression: 2,
  Sound: 1,
  Effects: 1,
  compilers: 21,
  ast: 1,
  minifier: 1,
  tc39: 1,
  "build tools": 3,
  iot: 5,
  "Personal Server": 1,
  "instant messaging": 4,
  "real time": 7,
  "distributed computing": 2,
  "distributed databases": 2,
  "app development": 2,
  "cross desktop": 1,
  monitoring: 4,
  devops: 10,
  "time-series": 1,
  research: 6,
  "internet freedom": 1,
  "internet censorship": 1,
  "computational biology": 3,
  physiology: 1,
  "pharmacological modeling": 1,
  visualization: 17,
  bioinformatics: 14,
  javascript: 3,
  "coding standards": 2,
  "life sciences": 1,
  games: 8,
  algorithms: 6,
  "c++": 4,
  "data structures": 4,
  "computer networking": 2,
  "future internet architecture": 1,
  geometry: 2,
  "2d/3d graphics": 3,
  "ray tracing": 1,
  "high-performance computing": 3,
  "deep neural net rendering": 1,
  mlearning: 1,
  "mobile app": 1,
  "web apps": 3,
  "embedded systems": 4,
  compilation: 1,
  security: 21,
  software: 2,
  geospatial: 2,
  "land rights": 1,
  geo: 1,
  "data visualization": 7,
  "image analysis": 1,
  "AI/ML": 6,
  microscopy: 1,
  "dicom pathology": 1,
  "web development": 10,
  "data science": 19,
  statistics: 5,
  "programming languages": 21,
  authorization: 1,
  IAM: 1,
  Authentication: 1,
  "software analysis": 1,
  optimization: 3,
  development: 2,
  "automated program repair": 1,
  genomics: 10,
  cancer: 1,
  "precision medicine": 1,
  "web applications": 13,
  "sepsis prediction": 1,
  "sepsis detection": 1,
  vr: 2,
  video: 13,
  subtitles: 2,
  concurrency: 3,
  parallel: 1,
  evented: 1,
  distributed: 3,
  "actor model": 1,
  hardware: 7,
  storage: 4,
  sensors: 1,
  callibration: 1,
  MLOps: 1,
  "Data Meshes": 1,
  "distributed systems": 4,
  "Software-Defined-Storage": 1,
  "numerical and data analysis software": 1,
  "simulation software": 1,
  algorithmics: 1,
  "particle physics": 1,
  "Performance Optimisation": 1,
  "mesh processing": 1,
  "computation geometry": 1,
  "geometry processing": 1,
  "open source software metrics": 1,
  "software sustainability": 1,
  "community building": 1,
  "security and software bill of materials": 1,
  "high performance computing": 3,
  "parallel computing": 2,
  "software engineering": 3,
  verification: 2,
  "programmer productivity": 1,
  "type systems": 1,
  "static code analysis‎": 2,
  "code review tool": 1,
  "coding conventions": 1,
  "artificial-intelligence": 1,
  soc: 1,
  "IP cores": 1,
  "ASIC design": 1,
  HDL: 1,
  chiplets: 1,
  browser: 2,
  "operating-system": 1,
  kernel: 12,
  "cloud-native": 1,
  pedagogy: 1,
  "digital logic design": 1,
  gis: 7,
  "civic tech": 5,
  analytics: 2,
  nonprofit: 5,
  crm: 1,
  "text analytics": 1,
  "text generation": 1,
  "functional programming": 6,
  "programming language": 2,
  "development tools": 5,
  "build systems": 2,
  "user interface": 3,
  "speech recognition": 1,
  pronunciation: 1,
  "cloud native": 4,
  observability: 4,
  chat: 3,
  "web application": 2,
  "network biology": 2,
  "internet of things": 3,
  "science and enineering": 1,
  "mesh generation": 1,
  "continuous delivery": 3,
  "great developer tooling": 3,
  desktop: 10,
  drivers: 7,
  firmware: 5,
  "boot loader": 1,
  BIOS: 2,
  copyleft: 1,
  "creative commons": 1,
  legal: 1,
  containers: 4,
  "Checkpoint/Restore": 1,
  linguistics: 3,
  History: 1,
  culture: 1,
  data: 6,
  dsl: 1,
  "convex optimization": 1,
  optimizations: 1,
  "object-oriented programming": 1,
  "system programming": 2,
  "mobile apps": 2,
  health: 3,
  infrastructure: 4,
  "open source": 4,
  "Data Infrastructure": 1,
  "semantic web": 4,
  "linked data": 2,
  "knowledge graph": 1,
  largelanguagemodel: 1,
  "CI/CD": 2,
  autopkgtest: 1,
  raspberrypi_builds: 1,
  mobian: 1,
  chemistry: 1,
  biology: 3,
  "materials science": 1,
  "Drug Discovery": 1,
  nlp: 4,
  conversational: 1,
  agent: 1,
  "data integration": 1,
  workflows: 2,
  "data security": 1,
  "ML/AL": 1,
  "open data": 7,
  "open government": 1,
  "public code": 1,
  humanitarian: 3,
  humanrights: 1,
  international: 1,
  global: 1,
  community: 4,
  forum: 3,
  asynchronous: 1,
  mathematics: 9,
  "scientific computing": 9,
  physics: 4,
  "partial differential equations": 1,
  python: 3,
  middleware: 3,
  "Embodied AI": 1,
  "Python Robotics": 1,
  "Autonomous Drive": 1,
  "Robot Dataflow": 1,
  DXP: 2,
  "Massive community": 1,
  Inclusive: 1,
  "data visualisation": 3,
  "earth observation": 1,
  "cloud databases": 2,
  "data-science": 4,
  automotive: 3,
  tools: 2,
  "cloud native java": 1,
  "iot & edge": 1,
  polyglot: 2,
  reactive: 1,
  unopionated: 1,
  search: 4,
  framework: 3,
  linter: 2,
  tooling: 2,
  parser: 1,
  rtos: 2,
  crawling: 1,
  "open science": 6,
  language: 3,
  messaging: 2,
  "soft real-time": 1,
  "programming-tools": 1,
  "functional-programming": 1,
  "runtime systems": 2,
  OS: 3,
  runtime: 1,
  platform: 3,
  "operating system": 3,
  LLM: 1,
  NetworkManager: 1,
  multimedia: 5,
  emulation: 2,
  disassembly: 3,
  decompilation: 1,
  "malware-analysis": 1,
  "reverse-engineering": 1,
  "flash chips": 1,
  "low level programming": 1,
  "data-intensive science": 1,
  "earth-system monitoring": 1,
  "space science": 1,
  libraries: 5,
  Fortran: 1,
  conference: 1,
  "rails application": 1,
  "video processing": 2,
  "event solutions": 2,
  spdx: 1,
  "license compliance": 2,
  "compliance automation": 2,
  "natural language understanding": 2,
  multilinguality: 1,
  "multimodal communication": 2,
  debug: 1,
  "electronic design tools": 1,
  "ui/ux": 1,
  cad: 1,
  architecture: 1,
  BIM: 1,
  CAM: 1,
  library: 6,
  fonts: 2,
  opentype: 1,
  truetype: 1,
  routing: 5,
  "wireless networks": 1,
  federation: 1,
  "music engraving": 1,
  "software defined networking": 3,
  systems: 1,
  "academic projects": 2,
  "game theory": 1,
  virtualization: 12,
  scanning: 1,
  "google cloud": 2,
  gaming: 2,
  "scientific visualization": 6,
  "data analysis": 3,
  communication: 5,
  bigdata: 1,
  hpc: 2,
  embedded: 5,
  init: 1,
  package: 1,
  "computational geometry": 2,
  "version control": 3,
  dvcs: 1,
  collaboration: 3,
  git: 2,
  editor: 2,
  DevSecOps: 2,
  genetics: 1,
  standards: 2,
  apps: 2,
  gnss: 1,
  geolocation: 2,
  navigation: 2,
  communications: 3,
  toolchain: 2,
  openmp: 1,
  "link time optimization": 1,
  design: 3,
  photography: 1,
  illustration: 1,
  mail: 1,
  "numerical computation": 3,
  "numerical methods": 1,
  matlab: 1,
  "command line": 1,
  "binary tools": 1,
  "real-time": 5,
  dsp: 1,
  "communications engineering": 1,
  cybersecurity: 2,
  "Software-Defined Radio": 1,
  cryptography: 2,
  TLS: 1,
  DTLS: 1,
  "cross-platform": 4,
  "game engine": 1,
  "game development": 3,
  programming: 2,
  Jax: 2,
  "AI,": 1,
  Gemma: 1,
  "global health": 2,
  "precision health": 1,
  "enteprise analytics": 1,
  packaging: 2,
  science: 9,
  geophysics: 1,
  electromagnetics: 1,
  "ground penetrating radar": 1,
  compiler: 6,
  "digital signal processing": 2,
  "function programming language": 1,
  "data and databases": 1,
  graphql: 1,
  "eletric mobility": 1,
  microservices: 3,
  "distributed networks": 2,
  "computer security": 2,
  "digital forensics": 1,
  sandbox: 2,
  network: 4,
  gui: 2,
  "programming tools": 3,
  "in memory data grid": 1,
  "data streaming": 1,
  "stream processing": 1,
  "data processing": 2,
  "e-health": 1,
  "global health and development": 1,
  "package manager": 1,
  macos: 2,
  Arts: 1,
  Humanities: 1,
  "web services": 2,
  "knowledge graphs": 2,
  "rest apis": 1,
  "brain modelling": 1,
  "neuroimage processing": 1,
  accessibility: 4,
  inclusion: 1,
  "language techology": 1,
  "input methods": 1,
  "medical simulation": 1,
  "medical research": 1,
  "virtual reality": 3,
  "software quality": 1,
  "software analytics": 1,
  perception: 1,
  "unreal engine": 1,
  imaging: 1,
  Codec: 1,
  "visual programming": 2,
  "game engines": 3,
  "creativity tools": 1,
  archiving: 1,
  internet: 2,
  dhcp: 1,
  dns: 1,
  ehealth: 1,
  "medical imaging": 3,
  "3D Reconstruction": 1,
  "3d printing": 1,
  Neuronavigation: 1,
  "data management": 1,
  Oceanography: 1,
  "Marine Biodiversity": 1,
  "computation graph": 1,
  "code conversion": 1,
  "unified API": 1,
  literature: 1,
  latex: 1,
  bibliography: 1,
  "model checking": 2,
  "symbolic execution": 2,
  "verification of concurrent systems": 2,
  "program analysis": 4,
  jvm: 1,
  keras: 1,
  "PYTHON LIBRARY": 1,
  kubernetes: 5,
  "continuous integration": 2,
  java: 1,
  "network analysis": 1,
  graphs: 2,
  "neural search": 1,
  "generative AI": 3,
  "Python MLOps Framework": 1,
  "Mulitmodel Data": 1,
  "video conferencing": 1,
  WebRTC: 2,
  cms: 3,
  database: 5,
  synchronisation: 1,
  "note-taking": 1,
  office: 1,
  "unit testing": 2,
  "software testing": 1,
  "framework development": 1,
  "user interface components": 1,
  "event handling": 1,
  ros: 1,
  "data validation": 1,
  "developer tooling": 1,
  email: 2,
  spatial: 1,
  applications: 1,
  "desktop environment": 1,
  "API Testing": 1,
  "Dev Tool": 1,
  "Functional Testing": 2,
  "AI Testing Agent": 1,
  sre: 2,
  CloudNative: 1,
  Operations: 1,
  offline: 3,
  tv: 1,
  "low-level": 1,
  "3D Geometry": 1,
  "software development": 1,
  "Programming & Build Tools": 1,
  "configuration management": 1,
  "scripting languages": 1,
  "kernel scripting": 1,
  "statically-typed languages": 1,
  edtech: 3,
  innovation: 1,
  "Social participation": 1,
  mentoring: 1,
  privacy: 5,
  vpn: 3,
  Circumvention: 1,
  learning: 1,
  "image prcessing": 1,
  "satellite data": 1,
  "orbital dynamics": 1,
  "space standards": 1,
  space: 2,
  "Communication Protocols": 1,
  Rover: 1,
  hfoss: 1,
  "office suite": 1,
  "desktop application": 1,
  "end user application": 2,
  "service mesh": 1,
  "cloud infrastructure": 1,
  maps: 4,
  ux: 1,
  "open hardware": 3,
  "package managers": 1,
  "science and medicine": 1,
  astronomy: 6,
  "package management": 1,
  "Operational Analytics": 1,
  "Database Engines": 1,
  "SQL Features": 1,
  "self-hosted": 1,
  interoperability: 1,
  decentralisation: 1,
  "Secure Messaging": 1,
  Marketing: 1,
  "Marketing Automation": 1,
  "Digital Marketing": 1,
  "Digital Experience Platform": 1,
  "multibody dynamics": 1,
  aeroelasticity: 1,
  "Structural engineering": 1,
  "computational-chemistry": 1,
  "high-performance-computing": 1,
  "molecular-simulation": 1,
  "machine-learning": 1,
  "news-media": 1,
  "media-analytics": 1,
  "civic-tech": 1,
  "ml-inference": 1,
  "Platform Engineering": 1,
  "cloud native infrastructure": 1,
  "infrastructure as design": 1,
  music: 5,
  books: 1,
  "music social network": 1,
  faas: 2,
  languages: 2,
  ffi: 1,
  "penetration testing": 1,
  "offensive security": 1,
  exploitation: 1,
  "mapping and surveying": 1,
  "graph algorithms": 1,
  Processor: 1,
  "System on Chip": 1,
  "RISC-V": 1,
  microkernel: 1,
  components: 1,
  ipc: 1,
  fintech: 2,
  "financial inclusion": 2,
  "mobile banking": 2,
  "digital financial services": 1,
  microfinance: 1,
  ios: 1,
  dj: 1,
  "Neural networks": 1,
  robot: 1,
  "web application security": 1,
  devtools: 3,
  alerting: 1,
  "climate monitoring": 1,
  "nature based solutions": 1,
  "land system modelling": 1,
  xr: 2,
  AR: 1,
  ide: 2,
  "mobile development": 1,
  "e-learning": 1,
  "school system": 1,
  "learning management": 1,
  "motion planning": 1,
  "trajectory generation": 1,
  kinematics: 1,
  game: 2,
  voxel: 2,
  minecraft: 1,
  modding: 1,
  "web browser": 1,
  "information security": 1,
  midi: 1,
  musicxml: 1,
  "sheet music": 1,
  "music notation": 1,
  cheminformatics: 2,
  "mass spectrometry": 1,
  "feature detection": 1,
  "informationc centric networking": 1,
  ipfs: 1,
  "text-editor": 1,
  "network monitoring": 2,
  "network security": 3,
  nonblocking: 1,
  async: 1,
  "Computer-Vision": 1,
  neuroanatomy: 1,
  "Application Development": 1,
  "End-To-End Testing": 1,
  "Component testing": 1,
  "Native mobile app testing": 1,
  declarative: 1,
  reproducible: 1,
  InfrastrucutreAsCode: 1,
  ipv6: 1,
  "network mapping": 1,
  blindness: 1,
  "screen reader": 1,
  braille: 2,
  "text to speech": 1,
  "UX/UI": 1,
  visualisation: 1,
  "solar physics": 2,
  "high energy astrophysics": 2,
  "orbital mechanics": 1,
  "Open Source Bioinformatics": 1,
  "quantum chemistry": 2,
  Forecasting: 1,
  Climate: 1,
  renewables: 1,
  "global development": 1,
  "social good": 1,
  electrophysiology: 1,
  ui: 3,
  environment: 2,
  food: 1,
  "data discovery": 1,
  "electronic medical records": 1,
  "Digital Public Goods": 1,
  "Telemedicine and Remote Care": 1,
  "AI in Health": 1,
  HMIS: 1,
  Control: 1,
  "fleet management": 1,
  "reproducible science": 1,
  "open-science": 1,
  government: 1,
  scraping: 1,
  "Artificial Inteligence": 1,
  Transit: 1,
  travel: 1,
  bus: 1,
  "3D machine learning": 1,
  "3D data processing": 1,
  "3D visualization": 1,
  "physically based rendering": 1,
  filesystems: 1,
  tracing: 2,
  php: 1,
  "Health Care": 1,
  "Laboratory Information System": 1,
  medicine: 1,
  "medical records": 1,
  "medical practice management solution": 1,
  "reverse engineering": 3,
  "e-mail": 1,
  encryption: 1,
  "encrypted computation": 1,
  "federated learning": 1,
  "structured transparency": 1,
  "differential privacy": 1,
  frontend: 1,
  "Electronic Medical Record System": 1,
  "QA automation": 1,
  webdev: 1,
  "data-wrangling": 1,
  reconcilation: 1,
  "data-mining": 1,
  voip: 1,
  telephony: 1,
  "real-time-communications": 1,
  sip: 1,
  geodata: 1,
  AIML: 1,
  "operating system developer tools": 1,
  "containers kubernetes": 1,
  "Security Cryptography": 1,
  "systems management": 1,
  "neural network": 1,
  inference: 1,
  "gen ai": 1,
  "network management system": 1,
  wifi: 1,
  sdn: 1,
  "open event": 1,
  "social impact": 1,
  "data mining": 1,
  "gui toolkit": 1,
  acoustics: 1,
  "community science": 1,
  "Data cataloging": 1,
  "enterprise application": 1,
  "enterprise information systems": 1,
  "application security": 1,
  sync: 1,
  "file share": 1,
  "live streaming": 1,
  p2p: 1,
  "reinforcement learning": 1,
  "web tools": 1,
  "ecosystem models": 1,
  "climate science": 1,
  "Ecological Forecasting,": 1,
  analyzing: 1,
  transcoding: 1,
  "pipeline automation": 1,
  "load testing": 1,
  alerts: 1,
  metrics: 1,
  performance: 1,
  "virtual machines": 1,
  Modelling: 1,
  "Live music": 1,
  social: 1,
  mysql: 1,
  developer: 1,
  administrator: 1,
  beacons: 1,
  voice: 1,
  filmmaking: 1,
  "video editing": 1,
  "network programming": 1,
  "code analysis": 1,
  "code quality": 1,
  "source code analyzer": 1,
  "school apps": 1,
  "gpu computing": 1,
  "polyhedral model": 1,
  polystore: 1,
  nosql: 1,
  "new projects": 1,
  "individual projects": 1,
  sql: 3,
  Benchmark: 1,
  documentation: 3,
  "DNS recursive solutions": 1,
  "Authoritative DNS software": 1,
  "probabilistic models": 1,
  bot: 1,
  "creative coding": 1,
  "Agent Based Models": 1,
  "Generative Science": 1,
  exoplanet: 1,
  "cultural heritage": 1,
  "computer-assisted translation": 1,
  "Kubernetes Operator": 1,
  realtime: 1,
  modeling: 1,
  Backup: 1,
  "Computational Science": 1,
  "numerical algorithms": 1,
  "Search Engines": 2,
  "systems programming": 1,
  emulator: 1,
  hypervisor: 1,
  mhealth: 1,
  "remote patient monitoring": 1,
  "micro-services": 1,
  devices: 1,
  debugging: 3,
  "ui toolkit": 1,
  "design system": 1,
  windows: 2,
  gesture: 1,
  Fairness: 1,
  Robustness: 1,
  Safety: 1,
  Interpretibility: 1,
  "component-based development": 1,
  "Multi-agent Systems": 1,
  "group chat": 1,
  "Team Collaboration": 1,
  "Chat platform": 1,
  "spam filtering": 1,
  multicore: 1,
  server: 1,
  application: 2,
  "linear algebra": 1,
  cli: 1,
  enterprise: 1,
  gpu: 1,
  "Serverless Computing": 1,
  "software preservation": 1,
  "software archeology": 1,
  rust: 2,
  Debugger: 1,
  "high performance": 1,
  tcp: 1,
  "user experience": 3,
  "project-management": 1,
  "time series": 2,
  "toolbox frameworks": 1,
  Telepresence: 1,
  "digital arts": 1,
  "software verification": 1,
  benchmarking: 1,
  "SAT & SMT solving": 1,
  "digital preservation": 1,
  "source code management": 1,
  floss: 1,
  "big code": 1,
  drones: 1,
  portable: 1,
  makers: 1,
  compliance: 1,
  licensing: 1,
  "Automated Testing": 1,
  "Logic bugs": 1,
  "Database systems": 1,
  "numerical computing": 1,
  "parallel algorithms": 1,
  hpx: 1,
  aerodynamics: 1,
  "Computational Fluid Dynamics": 1,
  "Multi-Disciplinary Optimization": 1,
  "Adjoint Design Optimization": 1,
  "Fluid Dynamics": 1,
  "biomedical data science": 1,
  "cancer informatics": 1,
  diagnostic: 1,
  "civil society": 1,
  "Security Defense": 1,
  "smart cities": 1,
  "privacy/security": 1,
  "component repository": 1,
  "vulnerabilities management": 1,
  Packages: 1,
  "Server development": 1,
  "Standard Libraries": 1,
  "symbolic mathematics": 1,
  "vector graphics": 1,
  "data processing pipeline": 1,
  "reliable log transfer": 1,
  logging: 1,
  "high-performance data processing": 1,
  "mobile applications": 1,
  "women in tech": 1,
  "peace corps": 1,
  "In-memory": 1,
  JIT: 1,
  IMDG: 1,
  "NoSQL Database": 1,
  astrophysics: 2,
  teaching: 1,
  "on-device machine learning": 1,
  other: 1,
  "game design": 1,
  "Embedded System": 1,
  honeypots: 1,
  "malware analysis": 1,
  "Threat Intelligence": 1,
  "test input generation": 1,
  math: 1,
  ipsec: 1,
  ikev2: 1,
  printing: 1,
  iio: 1,
  zephyr: 1,
  "embeddable widget": 1,
  "rare disease": 1,
  "data refinement": 1,
  userland: 1,
  unix: 1,
  bsd: 1,
  "network simulation": 1,
  "AI/ML Networking": 1,
  "networking security": 1,
  "programming languages and development tools": 1,
  "database services": 1,
  "declarative language": 2,
  "graphics / video / audio / virtual reality": 1,
  "anti-censorship": 1,
  "Human Rights": 1,
  Surveillance: 1,
  "visualization grammar": 1,
  "plotting tools": 1,
  compatibility: 1,
  directx: 1,
  opengl: 1,
  vulkan: 1,
  uefi: 1,
  edk2: 1,
  acpi: 1,
  edit: 1,
  level: 1,
  "algorithm prototyping/visualization": 1,
  fpga: 1,
  "formal methods": 1,
  multicloud: 1,
  cats: 1,
  "cancer research": 1,
  internationalization: 1,
  "software reuse": 1,
  "software configurability": 1,
  "local grammars": 1,
  "finite state automata": 1,
  "corpus annotation": 1,
  "multilingual language resources": 1,
  Usability: 1,
  "User Evaluation": 1,
  "Eye Tracking": 1,
  "Sentimental Analysis": 1,
  "distributed energy systems": 1,
  "modeling & optimization": 1,
  "data portal": 1,
  codecs: 1,
  "media database": 1,
  "multimedia retrieval": 1,
  Wayland: 1,
  ScreenCapture: 1,
  "Desktop Portals": 1,
  "window system": 1,
  display: 1,
  "Vector Database": 1,
  webassembly: 1,
  "Node.js": 1,
  webpack: 1,
  "genome analysis": 1,
  wikipedia: 1,
  wikimedia: 1,
  mediawiki: 1,
  i18n: 1,
  "fake-news": 1,
  misinformation: 1,
  decentralization: 1,
  bookmarking: 1,
  "micro services": 1,
  "api management": 1,
  "information retrieval": 1,
  indexing: 1,
  "home theater": 1,
  "cloud computing": 1,
  unikernels: 1,
  "embedded/automotive": 1,
  customization: 1,
  "text editor": 1,
  "video encode": 1,
  "video decode": 1,
  Jingle: 1,
  "Real-Time Communication": 1,
  "remote-access": 1,
  seamless: 1,
  "remote access": 1,
  "3dui": 1,
  "window management": 1,
  wiki: 1,
  "structured data": 1,
  AGI: 1,
  "content management": 1,
  "digital library": 1,
  "visual design": 1,
  "teaching quality codebase": 1,
  "team chat": 1,
  integrations: 1,
};

export const TECHS: Record<string, number> = {
  "c,c++": 35,
  ros: 7,
  opencv: 6,
  cmake: 9,
  boost: 1,
  javascript: 170,
  android: 33,
  java: 94,
  "web services": 2,
  "ogc standards": 1,
  python: 243,
  "Django+PostgreSQL": 1,
  "C/Rust/Go": 1,
  c: 80,
  opengl: 22,
  "c++": 106,
  rust: 36,
  json: 4,
  react: 31,
  "artificial intelligence": 4,
  "machine learning": 23,
  sdr: 3,
  sqlite: 3,
  "raspberry pi": 1,
  llvm: 9,
  fuzzing: 1,
  qemu: 3,
  "python 3": 6,
  mysql: 23,
  matlab: 3,
  dicom: 2,
  "ruby on rails": 13,
  golang: 25,
  swift: 6,
  "spir-v": 1,
  webgpu: 2,
  ios: 8,
  kotlin: 11,
  mobile: 1,
  flutter: 9,
  Blockchain: 1,
  sql: 8,
  arrow: 2,
  xml: 3,
  bash: 4,
  fpga: 6,
  nix: 2,
  rest: 3,
  openapi: 2,
  grpc: 4,
  "protocol buffers": 1,
  rpc: 1,
  api: 3,
  ai: 11,
  dart: 2,
  "ui/ux": 3,
  "c++11": 4,
  archc: 1,
  arduino: 2,
  lua: 9,
  pixhawk: 1,
  go: 23,
  typescript: 29,
  RAML: 1,
  qt: 19,
  wxwidgets: 1,
  VST: 1,
  "node.js": 25,
  babel: 1,
  windows: 3,
  bazel: 1,
  linux: 21,
  "risc-v": 4,
  dsp: 1,
  "Zephyr RTOS": 1,
  xmpp: 4,
  erlang: 2,
  docker: 20,
  elasticsearch: 4,
  "meteor.js": 1,
  vulkan: 8,
  "c++14": 4,
  "c++17": 2,
  "c++20": 1,
  "linux kernel": 4,
  xia: 1,
  "advanced data structures": 1,
  ddos: 1,
  opencl: 2,
  scripting: 3,
  django: 21,
  bootstrap: 2,
  shell: 5,
  "gnu make": 2,
  kconfig: 1,
  tensorflow: 12,
  javasc: 1,
  mongodb: 5,
  "r-project": 3,
  clang: 3,
  Bison: 1,
  OIDC: 1,
  OAuth: 1,
  scala: 8,
  bytecode: 1,
  flask: 2,
  reactjs: 5,
  ruby: 17,
  "multi-threading": 1,
  "multi-core": 1,
  zeromq: 1,
  "high-resolution timers": 1,
  robotics: 1,
  ceph: 1,
  postgres: 2,
  gpu: 4,
  LLMs: 2,
  "data analysis": 4,
  "container orchestration": 1,
  postgresql: 21,
  metrics: 1,
  chapel: 1,
  "high performance computing": 2,
  compilers: 2,
  Verification: 1,
  "formal methods": 1,
  "type systems": 1,
  antlr: 3,
  "artificial-intelligence": 1,
  chisel: 1,
  systemverilog: 2,
  ASIC: 1,
  git: 11,
  kubernetes: 17,
  ebpf: 3,
  rails: 2,
  canvas: 1,
  vue: 2,
  php: 18,
  angular: 10,
  clojure: 3,
  clojurescript: 1,
  jvm: 8,
  "functional programming": 3,
  angularjs: 3,
  aws: 2,
  "cross-platform": 1,
  "hidden markov models": 1,
  prometheus: 4,
  OpenTelemetry: 1,
  envoy: 1,
  haskell: 5,
  webgl: 2,
  html: 10,
  css: 10,
  jenkins: 2,
  tekton: 1,
  spinnaker: 1,
  ortelius: 1,
  "screwdriver.cd": 1,
  gtk: 9,
  assembly: 9,
  arm: 4,
  x86: 5,
  wordpress: 1,
  SCSS: 1,
  make: 4,
  d: 1,
  "C\\C++": 1,
  osx: 1,
  bsd: 2,
  dlang: 1,
  terraform: 2,
  "Distributed key-value store": 1,
  "Fault tolerant": 1,
  "Metadata management": 1,
  rdf: 2,
  perl: 7,
  numpy: 7,
  pytorch: 12,
  HuggingFace: 1,
  "python deep learning frameworks": 1,
  Colab: 1,
  "html,css,javascript": 1,
  "many more": 1,
  "html,css": 2,
  ember: 1,
  "Autonomous drive": 1,
  symfony: 3,
  "deep learning": 3,
  jupyter: 6,
  gdal: 1,
  rtos: 1,
  eclipsejavaide: 1,
  jakartaee: 1,
  softwaredefinedvehicles: 1,
  "reactive extensions": 1,
  microservices: 3,
  "event-loop": 1,
  Chromium: 1,
  elm: 2,
  gcc: 2,
  "google cloud": 2,
  elixir: 1,
  beam: 1,
  lfe: 1,
  webassembly: 4,
  rpm: 1,
  security: 1,
  Container: 1,
  asm: 4,
  "ida-pro": 1,
  Ghidra: 1,
  bios: 1,
  rom: 1,
  spi: 1,
  mpi: 3,
  fortran: 2,
  grafana: 3,
  voctomix: 1,
  influxdb: 1,
  verilog: 3,
  vhdl: 2,
  compiler: 1,
  "css,html": 1,
  OpenCASCADE: 1,
  OpenInventor: 1,
  autotools: 3,
  meson: 1,
  openwrt: 2,
  pyqt: 1,
  networking: 3,
  routing: 1,
  xen: 2,
  kvm: 4,
  virtualization: 1,
  "web development": 3,
  "game development": 1,
  yocto: 1,
  embedded: 1,
  automotive: 1,
  "some/ip": 1,
  nextflow: 2,
  r: 6,
  "github-actions": 1,
  "shell script": 3,
  "c language": 2,
  atom: 1,
  "c#": 4,
  Flatpak: 1,
  "gnu autotools": 1,
  GEGL: 1,
  "restful api": 1,
  sqlalchemy: 1,
  hg: 1,
  simd: 1,
  Cryptography: 1,
  TLS: 1,
  Jax: 3,
  Gemma: 1,
  fhir: 2,
  materialui: 2,
  cuda: 5,
  openmp: 1,
  graphql: 3,
  "apache spark": 2,
  "distributed systems": 5,
  cloud: 4,
  backend: 1,
  posix: 3,
  unix: 3,
  ghc: 1,
  gradle: 3,
  macos: 1,
  redis: 3,
  dtrace: 1,
  illumos: 1,
  openzfs: 1,
  zfs: 1,
  svg: 1,
  "communication protocol": 1,
  "a-frame": 1,
  neo4j: 1,
  "htc vive": 1,
  lisp: 2,
  "unreal engine": 1,
  Codec: 1,
  Media: 1,
  Imaging: 1,
  hadoop: 1,
  "apache kafka": 1,
  VueJS: 1,
  c99: 2,
  cython: 7,
  Vtk: 1,
  Zarr: 1,
  NetCDF: 1,
  javafx: 2,
  bibtex: 1,
  gazebo: 2,
  groovy: 1,
  gitops: 1,
  "data science": 5,
  "Multimodel AI": 1,
  webrtc: 2,
  electron: 1,
  "React-Native": 1,
  html5: 4,
  jquery: 1,
  ".net": 2,
  "JSON Schema": 2,
  jsonnet: 1,
  jinja2: 1,
  gis: 4,
  qml: 3,
  "data structures": 1,
  MERN: 1,
  Helm: 1,
  "vue.js": 3,
  ffmpeg: 3,
  fasm: 1,
  pci: 1,
  "Spatial AI": 1,
  "Parsers & Compilers": 1,
  Multiplatform: 1,
  "controller-runtime": 1,
  CEL: 1,
  YAML: 1,
  luarocks: 1,
  kernel: 1,
  lunatik: 1,
  pallene: 1,
  "jupyter hub": 1,
  qt5: 3,
  ansible: 1,
  gstreamer: 3,
  v4l2: 1,
  "embedded systems": 1,
  "rest api": 1,
  micropython: 1,
  "dart/flutter": 1,
  ci: 1,
  ssh: 1,
  sftp: 1,
  hypervisor: 1,
  lxc: 1,
  linkerd: 1,
  "Google Earth": 1,
  mlir: 2,
  tcl: 1,
  buildbot: 1,
  Rxjava: 1,
  Akka: 1,
  Netty: 1,
  "apache airflow": 1,
  visualization: 1,
  databases: 2,
  svelte: 1,
  "big data": 1,
  "visual design": 1,
  spark: 1,
  julia: 6,
  statistics: 1,
  RISCV: 1,
  Processor: 1,
  Hardware: 1,
  systemonchip: 1,
  memory: 1,
  spring: 3,
  gwt: 2,
  onnx: 1,
  "C++ template metaprogramming": 1,
  webs: 1,
  waf: 1,
  "web application firewall": 1,
  graphite: 1,
  "Data-Science": 1,
  openxr: 2,
  Graphics: 1,
  XR: 1,
  "f#": 1,
  ionic: 1,
  blender: 2,
  github: 7,
  jni: 1,
  Scipy: 1,
  napari: 1,
  selenium: 1,
  WebDriver: 1,
  "ui automation": 1,
  iaccessible2: 1,
  "win32 api": 1,
  numba: 3,
  "Git/GitHub": 1,
  "scikit-learn": 2,
  pandas: 4,
  HDF5: 1,
  caffe: 1,
  pcl: 1,
  juce: 1,
  graph: 1,
  NextJs: 2,
  "Open-RMF": 1,
  AST: 1,
  "Machine Learning (ML)": 1,
  "tcp/udp": 1,
  libusb: 1,
  openpgp: 1,
  "hyperledger aries": 1,
  "reactjs javascript": 1,
  emberjs: 1,
  "google app engine": 2,
  "Apache Beam": 1,
  "GitHub Actions": 2,
  OpenStreetMap: 1,
  d3: 3,
  middleware: 2,
  bpm: 1,
  wiki: 1,
  ZAP: 1,
  "Juice Shop": 1,
  sockets: 1,
  geospatial: 1,
  celery: 1,
  htop: 1,
  sysstat: 1,
  smalltalk: 1,
  pharo: 1,
  spec: 1,
  SUnit: 1,
  "html5/css3": 1,
  cakephp: 1,
  beacon: 1,
  "web bluetooth": 1,
  "physical web": 1,
  bluetooth: 1,
  concurrency: 1,
  javacc: 1,
  xpath: 1,
  firmware: 1,
  cad: 1,
  "computer vision": 1,
  polly: 1,
  isl: 1,
  ppcg: 1,
  "open hardware": 1,
  "language-agnostic": 1,
  AsyncAPI: 1,
  DNS: 1,
  "Vector Operations": 1,
  mediawiki: 1,
  "kubernetes operators": 1,
  Emscripten: 1,
  kafka: 2,
  "react native": 1,
  win32: 3,
  nt: 1,
  documentation: 1,
  sphinx: 2,
  nlp: 1,
  "Technical writing": 1,
  LLM: 2,
  "generative ai": 1,
  clickhouse: 1,
  rubygems: 1,
  smb: 1,
  cifs: 1,
  "scala.js": 1,
  "scala native": 1,
  Serverless: 1,
  scilab: 1,
  cpp: 2,
  framework: 1,
  dpdk: 1,
  tcp: 1,
  "video codecs": 1,
  esp32: 1,
  Quarkus: 1,
  WDL: 1,
  hpc: 1,
  gawk: 1,
  textual: 1,
  redux: 1,
  couchdb: 1,
  SpringBoot: 1,
  gtkmm: 1,
  keras: 1,
  "recursive-descent": 1,
  "POSIX shell": 1,
  "garbage-collection": 1,
  RFCs: 1,
  cups: 1,
  "fuzz-testing": 1,
  "semantic web": 1,
  "text mining": 1,
  "named entity recognition": 1,
  ontologies: 1,
  Z3: 1,
  "regular expressions": 1,
  perl6: 1,
  perl5: 1,
  operator: 1,
  patroni: 1,
  lwjgl: 1,
  web: 1,
  vega: 1,
  "vega-lite": 1,
  "d3.js": 1,
  directx: 1,
  uefi: 1,
  ocaml: 2,
  "tla+": 1,
  eclipse: 1,
  smt: 1,
  tokio_rs: 1,
  wasm: 1,
  VLSI: 1,
  unicode: 2,
  "assembly language": 1,
  Firebase: 1,
  "fast fluid dynamics": 1,
  video: 1,
  wayland: 4,
  Zig: 1,
  kms: 1,
  vectors: 1,
  "natural language processing": 2,
  "Cloud Storage": 1,
  Phyton: 1,
  pcap: 1,
  "browser extension": 1,
  datproject: 1,
  soa: 1,
  "distributed computing": 1,
  "gtk+": 1,
  cocoa: 1,
  x11: 1,
  DRM: 1,
  swig: 1,
  "free/netbsd": 1,
  "asm/c/c++": 1,
  vala: 1,
  "Objective C": 1,
  compression: 1,
  "remote access": 1,
  glib: 1,
  css3: 1,
  velocity: 1,
  midi: 1,
  "open-sound-control": 1,
};
