/*export const categories: Category = {
  "Science and medicine": 115,
  Data: 71,
  "Programming languages": 104,
  Web: 45,
  Other: 52,
  "Infrastructure and cloud": 47,
  "End user applications": 79,
  Media: 51,
  "Artificial Intelligence": 38,
  "Development tools": 36,
  "Operating systems": 35,
  Security: 27,
  "Social and communication": 18,
};*/

export const CATEGORIES: Record<string, number> = {
  "Science and medicine": 112,
  Data: 73,
  Security: 27,
  "Development tools": 36,
  Media: 51,
  "Programming languages": 103,
  "Artificial Intelligence": 38,
  "Operating systems": 35,
  Other: 49,
  "End user applications": 83,
  "Social and communication": 18,
  "Infrastructure and cloud": 47,
  Web: 44,
};

export const TOPICS: Record<string, number> = {
  robotics: 19,
  "3d": 3,
  slam: 2,
  mapping: 3,
  "point clouds": 2,
  "citizen science": 2,
  "spatial information infrastructures": 1,
  "open standards": 1,
  "data analytics": 5,
  Geoinformation: 1,
  dependencies: 1,
  vulnerabilities: 2,
  SoftwareCompositionAnalysis: 1,
  License: 1,
  SBOM: 1,
  graphics: 30,
  media: 6,
  animation: 5,
  "Visual Effects": 1,
  Film: 1,
  "natural language processing": 9,
  "data modeling": 1,
  "legal technology": 1,
  "contract management": 1,
  "document assembly": 1,
  "space applications": 2,
  "signal processing": 2,
  "software defined radio": 3,
  cubesats: 1,
  simulations: 1,
  fuzzing: 3,
  ci: 1,
  education: 28,
  "machine learning": 41,
  "artificial intelligence": 11,
  "open education": 1,
  "deep learning": 11,
  neuroscience: 5,
  radiology: 3,
  heathcare: 1,
  "Polar Science": 1,
  "operating systems": 7,
  networking: 15,
  streaming: 6,
  "web servers": 1,
  "mobile-apps": 1,
  "bug finding": 2,
  "developer tools": 7,
  web: 64,
  "mobile programming": 2,
  mobile: 15,
  "web programming": 2,
  android: 3,
  "user generated content": 1,
  Flashcards: 1,
  backend: 1,
  "machine translation": 1,
  "language technology": 1,
  "less-resources languages": 1,
  "computer vision": 14,
  linux: 8,
  camera: 2,
  "image processing": 5,
  "digital hardware design": 1,
  automation: 11,
  apis: 2,
  "code generation": 1,
  "api description": 1,
  testing: 6,
  api: 6,
  "app development": 3,
  simulation: 11,
  rendering: 5,
  "computer graphics": 1,
  "image synthesis": 1,
  "computer architecture": 1,
  "processor design": 1,
  simulators: 1,
  interactivity: 2,
  electronics: 1,
  Drone: 1,
  "autonomous vehicle": 1,
  UGV: 1,
  "unmanned vehicle": 1,
  engineering: 3,
  "system modelling": 1,
  "mathematical software": 2,
  solver: 1,
  cloud: 37,
  Architectures: 1,
  audio: 9,
  editing: 2,
  compression: 2,
  Sound: 1,
  Effects: 1,
  compilers: 20,
  ast: 1,
  minifier: 1,
  tc39: 1,
  "build tools": 3,
  iot: 5,
  ai: 21,
  "Personal Server": 1,
  "instant messaging": 4,
  "real time": 7,
  "distributed computing": 2,
  "distributed databases": 2,
  "cross desktop": 1,
  monitoring: 4,
  devops: 7,
  "time-series": 1,
  research: 6,
  "internet freedom": 1,
  "internet censorship": 1,
  "computational biology": 3,
  physiology: 1,
  "pharmacological modeling": 1,
  visualization: 16,
  bioinformatics: 14,
  javascript: 3,
  "coding standards": 2,
  "life sciences": 1,
  games: 8,
  algorithms: 4,
  "c++": 4,
  "data structures": 3,
  "computer networking": 2,
  "future internet architecture": 1,
  geometry: 2,
  "2d/3d graphics": 3,
  "ray tracing": 1,
  "high-performance computing": 3,
  "deep neural net rendering": 1,
  mlearning: 1,
  "mobile app": 1,
  "web apps": 3,
  "embedded systems": 4,
  compilation: 1,
  security: 19,
  software: 2,
  geospatial: 2,
  "land rights": 1,
  geo: 1,
  "data visualization": 7,
  "image analysis": 1,
  "AI/ML": 4,
  microscopy: 1,
  "dicom pathology": 1,
  "web development": 11,
  "data science": 20,
  statistics: 5,
  "programming languages": 17,
  authorization: 1,
  IAM: 1,
  Authentication: 1,
  "software analysis": 1,
  optimization: 3,
  development: 2,
  "automated program repair": 1,
  genomics: 9,
  cancer: 1,
  "big data": 9,
  "precision medicine": 1,
  "web applications": 13,
  "sepsis prediction": 1,
  "sepsis detection": 1,
  vr: 2,
  video: 13,
  subtitles: 2,
  concurrency: 3,
  parallel: 1,
  evented: 1,
  distributed: 3,
  "actor model": 1,
  databases: 8,
  hardware: 6,
  storage: 5,
  sensors: 1,
  callibration: 1,
  "Data Meshes": 1,
  "distributed systems": 4,
  "Software-Defined-Storage": 1,
  "numerical and data analysis software": 1,
  "simulation software": 1,
  algorithmics: 1,
  "particle physics": 1,
  "Performance Optimisation": 1,
  "mesh processing": 1,
  "computation geometry": 1,
  "geometry processing": 1,
  "Diversity Equity and Inclusion": 1,
  "open source software metrics": 1,
  "software sustainability": 1,
  "community building": 1,
  "security and software bill of materials": 1,
  "high performance computing": 4,
  "parallel computing": 2,
  "software engineering": 3,
  verification: 2,
  "programmer productivity": 1,
  "type systems": 1,
  "static code analysis‎": 2,
  "code review tool": 1,
  "coding conventions": 1,
  soc: 1,
  "IP cores": 1,
  "ASIC design": 1,
  HDL: 1,
  chiplets: 1,
  browser: 2,
  "operating-system": 1,
  kernel: 11,
  "cloud-native": 1,
  pedagogy: 1,
  "digital logic design": 1,
  gis: 7,
  "civic tech": 5,
  analytics: 2,
  nonprofit: 5,
  crm: 1,
  "text analytics": 1,
  "text generation": 1,
  "functional programming": 5,
  "programming language": 2,
  "development tools": 5,
  "build systems": 2,
  "user interface": 3,
  "speech recognition": 1,
  pronunciation: 1,
  "cloud native": 3,
  observability: 4,
  chat: 3,
  "web application": 2,
  "network biology": 2,
  "internet of things": 3,
  "science and enineering": 1,
  "mesh generation": 1,
  "continuous delivery": 3,
  "great developer tooling": 3,
  desktop: 10,
  drivers: 7,
  firmware: 4,
  "boot loader": 1,
  BIOS: 2,
  copyleft: 1,
  "creative commons": 1,
  legal: 1,
  containers: 5,
  "Checkpoint/Restore": 1,
  linguistics: 3,
  History: 1,
  culture: 1,
  data: 6,
  dsl: 1,
  "convex optimization": 1,
  "object-oriented programming": 1,
  "system programming": 2,
  "mobile apps": 2,
  health: 3,
  infrastructure: 4,
  "open source": 4,
  "Data Infrastructure": 1,
  "semantic web": 4,
  "linked data": 2,
  "knowledge graph": 1,
  "data extraction": 1,
  largelanguagemodel: 1,
  "CI/CD": 2,
  "Android SDK": 1,
  "HPC MPI Benchmarking": 1,
  chemistry: 1,
  biology: 3,
  "materials science": 1,
  "Drug Discovery": 1,
  nlp: 4,
  conversational: 1,
  agent: 1,
  "science and medicine": 2,
  "data integration": 1,
  workflows: 2,
  "ML/AL": 1,
  "open data": 7,
  "open government": 1,
  "public code": 1,
  humanitarian: 3,
  humanrights: 1,
  international: 1,
  global: 1,
  community: 4,
  forum: 3,
  asynchronous: 1,
  mathematics: 9,
  "scientific computing": 9,
  physics: 4,
  "partial differential equations": 1,
  python: 2,
  DXP: 2,
  "Massive community": 1,
  Inclusive: 1,
  "data visualisation": 3,
  "earth observation": 1,
  "cloud databases": 2,
  "data-science": 3,
  automotive: 3,
  tools: 2,
  "cloud native java": 1,
  "iot & edge": 1,
  polyglot: 2,
  reactive: 1,
  unopionated: 1,
  search: 4,
  framework: 3,
  linter: 2,
  tooling: 2,
  parser: 1,
  rtos: 2,
  crawling: 1,
  "open science": 5,
  language: 3,
  messaging: 2,
  "soft real-time": 1,
  "programming-tools": 1,
  "functional-programming": 1,
  "runtime systems": 2,
  OS: 3,
  runtime: 1,
  distribution: 1,
  multimedia: 5,
  emulation: 2,
  disassembly: 3,
  decompilation: 1,
  "malware-analysis": 1,
  "reverse-engineering": 1,
  "flash chips": 1,
  "low level programming": 1,
  "data-intensive science": 1,
  "earth-system monitoring": 1,
  "space science": 1,
  libraries: 5,
  Fortran: 1,
  conference: 1,
  "rails application": 1,
  "video processing": 2,
  spdx: 1,
  "license compliance": 1,
  "compliance automation": 1,
  "natural language understanding": 2,
  multilinguality: 1,
  "multimodal communication": 2,
  debug: 1,
  "web services": 3,
  "electronic design tools": 1,
  "ui/ux": 1,
  cad: 1,
  architecture: 1,
  CAM: 1,
  library: 6,
  fonts: 1,
  opentype: 1,
  truetype: 1,
  "open hardware": 4,
  routing: 6,
  "wireless networks": 1,
  federation: 1,
  "music engraving": 1,
  "software defined networking": 3,
  systems: 1,
  "academic projects": 2,
  "game theory": 1,
  virtualization: 12,
  scanning: 1,
  "google cloud": 2,
  gaming: 2,
  "scientific visualization": 6,
  "data analysis": 2,
  communication: 5,
  bigdata: 1,
  hpc: 2,
  embedded: 5,
  init: 1,
  package: 1,
  "computational geometry": 2,
  "version control": 3,
  dvcs: 1,
  collaboration: 2,
  git: 1,
  editor: 2,
  genetics: 1,
  standards: 2,
  apps: 2,
  gnss: 1,
  geolocation: 2,
  navigation: 2,
  communications: 3,
  toolchain: 2,
  openmp: 1,
  "link time optimization": 1,
  design: 4,
  photography: 1,
  illustration: 1,
  mail: 1,
  "numerical computation": 3,
  "numerical methods": 1,
  matlab: 1,
  "command line": 1,
  "binary tools": 1,
  "real-time": 5,
  dsp: 1,
  "communications engineering": 1,
  cybersecurity: 2,
  "Software-Defined Radio": 1,
  cryptography: 2,
  TLS: 1,
  DTLS: 1,
  "cross-platform": 4,
  "game engine": 1,
  "game development": 3,
  programming: 3,
  "global health": 2,
  "precision health": 1,
  "enteprise analytics": 1,
  packaging: 2,
  science: 9,
  geophysics: 1,
  electromagnetics: 1,
  "ground penetrating radar": 1,
  compiler: 6,
  "digital signal processing": 2,
  "function programming language": 1,
  "data and databases": 1,
  graphql: 1,
  "eletric mobility": 1,
  middleware: 2,
  microservices: 3,
  "distributed networks": 2,
  "computer security": 2,
  "digital forensics": 1,
  sandbox: 2,
  network: 4,
  gui: 3,
  "programming tools": 3,
  "in memory data grid": 1,
  "data streaming": 1,
  "stream processing": 1,
  "data processing": 2,
  "e-health": 1,
  "global health and development": 1,
  "package manager": 1,
  macos: 2,
  Arts: 1,
  Humanities: 1,
  "knowledge graphs": 2,
  "rest apis": 1,
  "brain modelling": 1,
  "neuroimage processing": 1,
  accessibility: 5,
  inclusion: 1,
  "language techology": 1,
  "input methods": 1,
  "medical simulation": 1,
  "medical research": 1,
  "virtual reality": 3,
  "software quality": 1,
  "software analytics": 1,
  perception: 1,
  "unreal engine": 1,
  imaging: 1,
  Codec: 1,
  "visual programming": 2,
  "game engines": 3,
  "creativity tools": 1,
  archiving: 1,
  internet: 2,
  dhcp: 1,
  dns: 1,
  ehealth: 1,
  "medical imaging": 3,
  "3D Reconstruction": 1,
  "3d printing": 1,
  Neuronavigation: 1,
  "data management": 1,
  Oceanography: 1,
  "computation graph": 1,
  "code conversion": 1,
  "unified API": 1,
  literature: 1,
  latex: 1,
  bibliography: 1,
  "model checking": 2,
  "symbolic execution": 2,
  "verification of concurrent systems": 2,
  "program analysis": 4,
  jvm: 1,
  kubernetes: 4,
  "continuous integration": 2,
  java: 1,
  "network analysis": 1,
  graphs: 2,
  "neural search": 1,
  "generative AI": 2,
  "Python MLOps Framework": 1,
  "Mulitmodel Data": 1,
  "video conferencing": 1,
  WebRTC: 2,
  cms: 3,
  database: 6,
  synchronisation: 1,
  "note-taking": 1,
  office: 1,
  "unit testing": 2,
  "software testing": 1,
  "framework development": 1,
  "user interface components": 1,
  "event handling": 1,
  ros: 1,
  "data validation": 1,
  "developer tooling": 1,
  email: 2,
  spatial: 1,
  applications: 1,
  "desktop environment": 1,
  "API Testing": 1,
  "No code platform": 1,
  "Dev Tool": 1,
  "Functional Testing": 2,
  "Mock and Stubs Generation": 1,
  sre: 2,
  CloudNative: 1,
  Operations: 1,
  offline: 3,
  tv: 1,
  "operating system": 2,
  "low-level": 1,
  "software development": 1,
  "Programming & Build Tools": 1,
  "scripting languages": 1,
  "kernel scripting": 1,
  "statically-typed languages": 1,
  edtech: 3,
  innovation: 1,
  "Social participation": 1,
  mentoring: 1,
  privacy: 5,
  vpn: 3,
  Circumvention: 1,
  learning: 1,
  "image prcessing": 1,
  "satellite data": 1,
  "orbital dynamics": 1,
  "space standards": 1,
  space: 2,
  "Communication Protocols": 1,
  Rover: 1,
  hfoss: 1,
  "office suite": 1,
  "desktop application": 1,
  "end user application": 2,
  "service mesh": 1,
  "cloud infrastructure": 1,
  maps: 4,
  ux: 1,
  "package managers": 1,
  astronomy: 6,
  "package management": 1,
  "Operational Analytics": 1,
  "Database Engines": 1,
  "SQL Features": 1,
  "self-hosted": 1,
  interoperability: 1,
  decentralisation: 1,
  "Secure Messaging": 1,
  Marketing: 1,
  "Marketing Automation": 1,
  "Digital Marketing": 1,
  "Digital Experience Platform": 1,
  "multibody dynamics": 1,
  aeroelasticity: 1,
  "Structural engineering": 1,
  "computational-chemistry": 1,
  "high-performance-computing": 1,
  "molecular-simulation": 1,
  "soft-matter-physics": 1,
  "news-media": 1,
  "media-analytics": 1,
  "civic-tech": 1,
  "ml-inference": 1,
  music: 5,
  books: 1,
  "music social network": 1,
  faas: 2,
  languages: 2,
  ffi: 1,
  "penetration testing": 1,
  "offensive security": 1,
  exploitation: 1,
  "mapping and surveying": 1,
  "graph algorithms": 1,
  Processor: 1,
  "System on Chip": 1,
  "RISC-V": 1,
  microkernel: 1,
  components: 1,
  ipc: 1,
  fintech: 2,
  "financial inclusion": 2,
  "mobile banking": 2,
  "digital financial services": 1,
  microfinance: 1,
  ios: 1,
  dj: 1,
  "Neural networks": 1,
  robot: 1,
  "web application security": 1,
  devtools: 2,
  alerting: 1,
  "climate monitoring": 1,
  "nature based solutions": 1,
  "land system modelling": 1,
  xr: 2,
  AR: 1,
  ide: 2,
  "mobile development": 1,
  "e-learning": 1,
  "school system": 1,
  "learning management": 1,
  "motion planning": 1,
  "trajectory generation": 1,
  kinematics: 1,
  game: 2,
  voxel: 2,
  minecraft: 1,
  modding: 1,
  "web browser": 1,
  "information security": 1,
  midi: 1,
  musicxml: 1,
  "sheet music": 1,
  "music notation": 1,
  cheminformatics: 2,
  "mass spectrometry": 1,
  "feature detection": 1,
  "informationc centric networking": 1,
  ipfs: 1,
  "network monitoring": 2,
  "network security": 3,
  nonblocking: 1,
  async: 1,
  "Application Development": 1,
  "End-To-End Testing": 1,
  "Component testing": 1,
  "Native mobile app testing": 1,
  declarative: 1,
  reproducible: 1,
  InfrastrucutreAsCode: 1,
  ipv6: 1,
  "network mapping": 1,
  blindness: 1,
  "screen reader": 1,
  braille: 2,
  "text to speech": 1,
  "UX/UI": 1,
  visualisation: 1,
  "solar physics": 2,
  "high energy astrophysics": 2,
  "orbital mechanics": 1,
  "Open Source Bioinformatics": 1,
  "quantum chemistry": 2,
  Forecasting: 1,
  Climate: 1,
  renewables: 1,
  "global development": 1,
  "social good": 1,
  electrophysiology: 1,
  ui: 3,
  environment: 2,
  food: 1,
  "data discovery": 1,
  "electronic medical records": 1,
  "Digital Public Goods": 1,
  "Pandemic Response and Management": 1,
  "Telemedicine and Remote Care": 1,
  "AI in Health": 1,
  "fleet management": 1,
  "reproducible science": 1,
  government: 1,
  scraping: 1,
  "Artificial Inteligence": 1,
  Transit: 1,
  travel: 1,
  bus: 1,
  "3D machine learning": 1,
  "3D data processing": 1,
  "3D visualization": 1,
  "physically based rendering": 1,
  filesystems: 1,
  tracing: 2,
  php: 1,
  "Health Care": 1,
  "Laboratory Information System": 1,
  medicine: 1,
  "medical records": 1,
  "medical practice management solution": 1,
  "reverse engineering": 3,
  "e-mail": 1,
  encryption: 1,
  "encrypted computation": 1,
  "federated learning": 1,
  "structured transparency": 1,
  "differential privacy": 1,
  platform: 2,
  frontend: 1,
  "Electronic Medical Record System": 1,
  "QA automation": 1,
  "data-wrangling": 1,
  reconcilation: 1,
  "data-mining": 1,
  voip: 1,
  telephony: 1,
  "real-time-communications": 1,
  sip: 1,
  geodata: 1,
  AIML: 1,
  "operating system developer tools": 1,
  "containers kubernetes": 1,
  "Security Cryptography": 1,
  "systems management": 1,
  "neural network": 1,
  inference: 1,
  "gen ai": 1,
  "network management system": 1,
  wifi: 1,
  sdn: 1,
  "open event": 1,
  "event solutions": 1,
  "social impact": 1,
  "data mining": 1,
  "gui toolkit": 1,
  acoustics: 1,
  "community science": 1,
  "Data cataloging": 1,
  "enterprise application": 1,
  "enterprise information systems": 1,
  "application security": 1,
  DevSecOps: 1,
  sync: 1,
  "file share": 1,
  "live streaming": 1,
  p2p: 1,
  "ecosystem models": 1,
  "climate science": 1,
  "Ecological Forecasting,": 1,
  analyzing: 1,
  transcoding: 1,
  "pipeline automation": 1,
  "load testing": 1,
  alerts: 1,
  metrics: 1,
  performance: 1,
  "virtual machines": 1,
  Modelling: 1,
  social: 1,
  mysql: 1,
  developer: 1,
  administrator: 1,
  beacons: 1,
  voice: 1,
  filmmaking: 1,
  "video editing": 1,
  "network programming": 1,
  "code analysis": 1,
  "code quality": 1,
  "source code analyzer": 1,
  "school apps": 1,
  "gpu computing": 1,
  "polyhedral model": 1,
  polystore: 1,
  nosql: 1,
  "new projects": 1,
  "individual projects": 1,
  sql: 3,
  Benchmark: 1,
  documentation: 3,
  "DNS recursive solutions": 1,
  "Authoritative DNS software": 1,
  "probabilistic models": 1,
  bot: 1,
  "creative coding": 1,
  "Agent Based Models": 1,
  "Generative Science": 1,
  exoplanet: 1,
  "cultural heritage": 1,
  "computer-assisted translation": 1,
  "Kubernetes Operator": 1,
  realtime: 1,
  modeling: 1,
  Backup: 1,
  "Computational Science": 1,
  "numerical algorithms": 1,
  "Search Engines": 2,
  "systems programming": 1,
  emulator: 1,
  hypervisor: 1,
  mhealth: 1,
  "remote patient monitoring": 1,
  "micro-services": 1,
  devices: 1,
  debugging: 3,
  "ui toolkit": 1,
  "design system": 1,
  windows: 2,
  gesture: 1,
  Fairness: 1,
  Robustness: 1,
  Safety: 1,
  Interpretibility: 1,
  "component-based development": 1,
  "Multi-agent Systems": 1,
  "group chat": 1,
  "Team Collaboration": 1,
  "Chat platform": 1,
  "spam filtering": 1,
  multicore: 1,
  server: 1,
  application: 2,
  "linear algebra": 1,
  cli: 1,
  enterprise: 1,
  "Serverless Computing": 1,
  "software preservation": 1,
  "software archeology": 1,
  rust: 2,
  Debugger: 1,
  "high performance": 1,
  tcp: 1,
  "user experience": 2,
  "project-management": 1,
  "time series": 2,
  "toolbox frameworks": 1,
  "software verification": 1,
  benchmarking: 1,
  "formal methods": 2,
  "SAT & SMT solving": 1,
  "digital preservation": 1,
  "source code management": 1,
  floss: 1,
  "big code": 1,
  drones: 1,
  portable: 1,
  makers: 1,
  compliance: 1,
  licensing: 1,
  "Automated Testing": 1,
  "Logic bugs": 1,
  "Database systems": 1,
  "numerical computing": 1,
  "parallel algorithms": 1,
  hpx: 1,
  aerodynamics: 1,
  "Computational Fluid Dynamics": 1,
  "Multi-Disciplinary Optimization": 1,
  "Adjoint Design Optimization": 1,
  "Fluid Dynamics": 1,
  "biomedical data science": 1,
  "cancer informatics": 1,
  diagnostic: 1,
  "civil society": 1,
  "Security Defense": 1,
  "smart cities": 1,
  "privacy/security": 1,
  Packages: 1,
  "Server development": 1,
  "Standard Libraries": 1,
  "symbolic mathematics": 1,
  "vector graphics": 1,
  "data processing pipeline": 1,
  "reliable log transfer": 1,
  logging: 1,
  "high-performance data processing": 1,
  "mobile applications": 1,
  "women in tech": 1,
  "peace corps": 1,
  "In-memory": 1,
  JIT: 1,
  IMDG: 1,
  "NoSQL Database": 1,
  astrophysics: 2,
  teaching: 1,
  "on-device machine learning": 1,
  other: 1,
  "game design": 1,
  "Embedded System": 1,
  honeypots: 1,
  "malware analysis": 1,
  "Threat Intelligence": 1,
  "test input generation": 1,
  math: 1,
  ipsec: 1,
  ikev2: 1,
  printing: 1,
  iio: 1,
  zephyr: 1,
  "embeddable widget": 1,
  "rare disease": 1,
  "data refinement": 1,
  userland: 1,
  unix: 1,
  bsd: 1,
  "network simulation": 1,
  "formal verification": 1,
  "programmable data plane": 1,
  "programming languages and development tools": 1,
  "database services": 1,
  "declarative language": 2,
  "graphics / video / audio / virtual reality": 1,
  "anti-censorship": 1,
  "Human Rights": 1,
  Surveillance: 1,
  "visualization grammar": 1,
  "plotting tools": 1,
  compatibility: 1,
  directx: 1,
  opengl: 1,
  vulkan: 1,
  uefi: 1,
  edk2: 1,
  acpi: 1,
  edit: 1,
  level: 1,
  "algorithm prototyping/visualization": 1,
  fpga: 1,
  multicloud: 1,
  "I/O": 1,
  "cancer research": 1,
  internationalization: 1,
  "software reuse": 1,
  "software configurability": 1,
  "local grammars": 1,
  "finite state automata": 1,
  "corpus annotation": 1,
  "multilingual language resources": 1,
  Usability: 1,
  "User Evaluation": 1,
  "Heuristic Evaluation": 1,
  "Eye Tracking": 1,
  "Sentimental Analysis": 1,
  "distributed energy systems": 1,
  "modeling & optimization": 1,
  "data portal": 1,
  codecs: 1,
  "media database": 1,
  "multimedia retrieval": 1,
  Wayland: 1,
  ScreenCapture: 1,
  "Wayland Compositor": 1,
  "Desktop Portals": 1,
  "window system": 1,
  display: 1,
  "Vector Database": 1,
  webassembly: 1,
  "Node.js": 1,
  webpack: 1,
  "genome assembly": 1,
  "genome analysis": 1,
  wikipedia: 1,
  wikimedia: 1,
  mediawiki: 1,
  i18n: 1,
  "fake-news": 1,
  misinformation: 1,
  decentralization: 1,
  bookmarking: 1,
  "micro services": 1,
  "api management": 1,
  "information retrieval": 1,
  indexing: 1,
  "home theater": 1,
  "cloud computing": 1,
  unikernels: 1,
  "embedded/automotive": 1,
  customization: 1,
  "text editor": 1,
  "video encode": 1,
  "video decode": 1,
  Jingle: 1,
  "Real-Time Communication": 1,
  "remote-access": 1,
  seamless: 1,
  "remote access": 1,
  "3dui": 1,
  "window management": 1,
  wiki: 1,
  "structured data": 1,
  "content management": 1,
  "digital library": 1,
  "visual design": 1,
  "teaching quality codebase": 1,
  "team chat": 1,
  integrations: 1,
};

export const YEARS: number[] = [
  2024, 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016,
];
